### ISSUE TITLE
ServerZlibStorage broken on ZODB 5

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zc.zlibstorage#5]
Now that the DB's `__init__` method goes through `Connection.get()` to find the root object, the root object needs to be unpickled...but ServerZlibStorage copies the `load` method from the underlying storage, and hence doesn't decompress the root (if required). Thus the DB constructor blows up with `UnpicklingError`.

In ZODB 4, this wasn't an issue because `DB.__init__` simply asked the storage to `load` the data and didn't try to unpickle it, relying on the POSKeyError to inform it of a missing object.

**Comment by jamadden** [comment]
It seems possible this is just a test issue, but I'm not entirely sure. 

In test_mixed_compressed_and_uncompressed_and_packing, the doctest creates a FileStorage DB and writes some uncompressed records to it, then wraps with with a ZlibStorage and writes some compressed records to it (including the root). Then it tries to create a DB using a bunch of different storage wrappers, packing each time. Doing so using `ZlibStorage(compress=True)` and `ZlibStorage(compress=False)` work (as expected). But then the next snippet, `ServerZlibStorage(compress=False)` fails as described above:

```
Failed example:
    db = ZODB.DB(zc.zlibstorage.ServerZlibStorage(
        ZODB.FileStorage.FileStorage('data.fs', blob_dir='blobs'),
        compress=False))
Exception raised:
    Traceback (most recent call last):
      File "//2.7/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest zc.zlibstorage.tests.test_mixed_compressed_and_uncompressed_and_packing[38]>", line 3, in <module>
        compress=False))
      File "//lib/python2.7/site-packages/ZODB/DB.py", line 474, in __init__
        conn.get(z64)
      File "//lib/python2.7/site-packages/ZODB/Connection.py", line 246, in get
        obj = self._reader.getGhost(p)
      File "//lib/python2.7/site-packages/ZODB/serialize.py", line 587, in getGhost
        klass = unpickler.load()
    UnpicklingError: bad pickle data
```

It's not clear to me that this is something that would actually happen. The "usual" way to get such a ServerZlibStorage would be in a ZEO configuration in a ZEO server (where it is never wrapped with a DB), and ZEO exposes its own pack method. 

On the other hand, I think it's entirely possible to read the ZEO configuration file "manually" and create a DB in that way (for offline packing, perhaps?). README.txt contains an example of doing exactly that:
```
    %import zc.zlibstorage

    <zeo>
      address 8100
    </zeo>

    <serverzlibstorage>
      <filestorage>
        path data.fs
      </filestorage>
    </serverzlibstorage>

.. -> src

    >>> src = src[:src.find('<zeo>')]+src[src.find('</zeo>')+7:]

    >>> storage = ZODB.config.storageFromString(src)
    >>> storage.transform_record_data(data) == b'.z'+zlib.compress(data)
    True
    >>> storage.__class__.__name__
    'ServerZlibStorage'
``

**Comment by jamadden** [comment]
(Also, the next stanza begins "using the server storage in non-compress mode:" and *also* constructs a `ServerZlibStorage(compress=False)`, so there's either a redundant block, or this block is misdescribed and should be passing compress=True. AFAICS it's always been this way, though.)
